sonar.projectKey=PruebasCalidad
sonar.organization=oscarB1026
sonar.projectName=oscarB1026_PruebasCalidad
sonar.projectVersion=1.0.0
#Se agregó nueva configuración

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.java.libraries=target/dependency/*.jar

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=target/surefire-reports

sonar.exclusions=**/*Application.java,**/*Config.java,**/*Entity.java,**/dto/**,**/exception/**

sonar.coverage.exclusions=**/*Application.java,**/*Config.java,**/*Entity.java,**/dto/**,**/exception/**

sonar.cpd.exclusions=**/*Test.java,**/*IT.java

sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S112
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.java
sonar.issue.ignore.multicriteria.e2.ruleKey=java:S1192
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.java