name: SonarCloud Analysis - LogiTrack

on:
  push:
    branches: [ main, develop, feature/dtangarife]
  pull_request:
    branches: [ main, develop, feature/dtangarife]

jobs:
  sonar:
    name: Build, Test & Analyze
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: logitrack
          POSTGRES_USER: logitrack_user
          POSTGRES_PASSWORD: logitrack_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build, test and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/logitrack
          SPRING_DATASOURCE_USERNAME: logitrack_user
          SPRING_DATASOURCE_PASSWORD: logitrack_pass
        run: |
          mvn verify sonar:sonar \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.organization=andrest3086  \
            -Dsonar.projectKey=AndresT3086_PruebasUnitarias \
            -Dsonar.host.url=https://sonarcloud.io